# 03 Pandas②

#### 주의 : 판다스의 모든 것을 다루지 않습니다. Machine Learning 또는 Deep Learning을 공부하기 위해 최소한 알아야 하는 범위만을 다룹니다.

## 0.라이브러리 불러오기 & 데이터 업로드

* 라이브러리 불러오는 방법과 별칭(alias)

In [ ]:
import pandas as pd
import numpy as np

## 2.Pandas Dataframe

### 2.6 Group by

In [ ]:
# 다시 불러옵시다.
df = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/Graduate_apply.csv')
df.head()

In [ ]:
# rank 별 gre 평균 점수를 조회해보자.
#as_index = True이면 결과가 series로 나옴.
df.groupby(by=['rank'], as_index = False)['gre'].mean()

In [ ]:
# rank별 admit 별 gre와 gpa 평균 점수를 조회
df1 = df.groupby(by = ['rank', 'admit'], as_index=False)['gre', 'gpa'].mean()
df1

In [ ]:
# rank별 admit 별 count 조회
df2 = df.groupby(by = ['rank', 'admit'], as_index=False)['gre'].count()
df2

두 dataframe의 칼럼이름을 변경하고 하나로 합쳐봅시다.

In [ ]:
df1.rename(columns={'gre':'gre_mean', 'gpa':'gpa_mean'}, inplace = True)
df1

In [ ]:
df2.rename(columns={'gre':'count'}, inplace = True)
df2

In [ ]:
df2[["count"]]

In [ ]:
df_new = pd.concat([df1, df2], axis=1)
df_new

### 실습1 : Group by①

In [ ]:
# 1) https://raw.githubusercontent.com/DA4BAM/dataset/master/garak_market_price.CSV 을 읽고, g_price에 담습니다.

In [ ]:
# 2) ProductName 별 최대 Price를 출력하시오.

In [ ]:
# 3) ProductName 별, 등급별  최대 Price를 출력하시오.

### 실습1 : Group by①

In [ ]:
# 1) pandas read_csv 함수를 이용하여 
# https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic_simple.csv 을 읽고, 
# titanic 에 담습니다.

In [ ]:
# 2) 성별 별 평균 Fare을 출력하시오.

In [ ]:
# 3) Embarked 별, 성별 별  평균 Price를 출력하시오.

### 2.7 Join(Merge)

In [ ]:
# 두 데이터셋을 불러옵니다.
g_in = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/garak_market_in.CSV')
g_price = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/garak_market_price.CSV')

In [ ]:
# 복습1 : g_price에서 칼럼을 추가하시오
# 1kg 당 가격 (Unit_Price)

g_price.head()

In [ ]:
# 복습2 : 위 결과에 이어서, g_price에서 Date 별, ProductID별 평균 Price를 구하여 g_price2에 저장하시오.

In [ ]:
# 복습3 : 칼렴 명 Unit_Price를 Avg_Price로 변경하시오.

* 판다스에서 join은 굉장히 간단합니다.
* 자동으로 key를 잡아줍니다
* default로 inner join을 합니다.

In [ ]:
g_in.head()

In [ ]:
g_price2.head()

In [ ]:
# 공통된 칼럼이 있으면 그 칼럼을 key로 사용
# 위 head() 결과에서 공통된 칼럼은 무엇인가요?

In [ ]:
# 이제 merge를 시도해 봅시다.

pd.merge(g_price2, g_in)

### 실습 : Join(Merge)

조금 복잡한 데이터 가지고 연습을 해 봅시다.  
Merge는 아래와 같은 상황에서 주로 사용됩니다!

* sales : 판매 정보
* products : 상품정보

In [ ]:
sales = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/sales.csv')
sales.head()

In [ ]:
products = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/products.csv')
products.head()

In [ ]:
# sales를 가지고 집계를 먼저 해 봅시다.
# 상품ID별로 매출액(Amt)의 합계를 구해 봅시다.

In [ ]:
# 2) 상품이름(ProductName)별로 매출액(Amt)의 합계를 구해봅시다.
# 그리고 매출액이 높은 순으로 정렬해 봅시다.

In [ ]:
# 3) Category 별로 매출액을 집계하고 매출액이 높은 순으로 정렬해 봅시다.

### 2.8 날짜 다루기

In [ ]:
g_price = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/garak_market_price.CSV')
g_price.head()

* 날짜 타입으로 변환합니다.

In [ ]:
g_price['Date'] = pd.to_datetime(g_price['Date'], format='%Y%m%d')

* 날짜 타입으로 변환하면, 날짜로 부터 날짜의 요소들을 추출할 수 있습니다.

In [ ]:
# 연도
g_price.Date.dt.year

In [ ]:
# 월
g_price.Date.dt.month

In [ ]:
# 주차
g_price.Date.dt.weekofyear

In [ ]:
# 요일
g_price.Date.dt.dayofweek

In [ ]:
# g_price에 월을 추가합시다.
g_price['Month'] = g_price.Date.dt.month
g_price.head()

### 2.9 Concat

데이터 프레임을 위/아래로, 양 옆으로 붙여 봅시다.

In [ ]:
# 고구마이면서 특급(0)의 월별 평균 가격을 조회해 봅시다.
g_price.loc[(g_price['ProductName'] == '고구마') & (g_price['Grade'] == 0 )].groupby('Month', as_index = False)['Price'].mean()

In [ ]:
# 고구마이면서 grade 0, 1 등급의 월별 평균 가격을 각각 저장해 봅시다.
sp_0 = g_price.loc[(g_price['ProductName'] == '고구마') & (g_price['Grade'] == 0 )].groupby('Month', as_index = False)['Price'].mean()
sp_1 = g_price.loc[(g_price['ProductName'] == '고구마') & (g_price['Grade'] == 1 )].groupby('Month', as_index = False)['Price'].mean()

In [ ]:
# 칼럼 이름 수정
sp_0.columns.values[1] = '특_평균가격'
sp_0.head()

In [ ]:
sp_1.columns.values[1] = '상_평균가격'
sp_1.head()

In [ ]:
# 이제 concat 열 기준으로 붙여 봅시다.
pd.concat([sp_0 , sp_1], axis=1)

In [ ]:
# 월이 중복되는군요. 오른쪽은 제외하고 합쳐봅시다.
pd.concat([sp_0 , sp_1.iloc[:,1]], axis=1)